//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelUygulamasi.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusteriBilgileri", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class MusteriBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CikisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GirisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MusteriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OdaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UcretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CikisTarihi {
            get {
                return this.CikisTarihiField;
            }
            set {
                if ((this.CikisTarihiField.Equals(value) != true)) {
                    this.CikisTarihiField = value;
                    this.RaisePropertyChanged("CikisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GirisTarihi {
            get {
                return this.GirisTarihiField;
            }
            set {
                if ((this.GirisTarihiField.Equals(value) != true)) {
                    this.GirisTarihiField = value;
                    this.RaisePropertyChanged("GirisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((this.MusteriIdField.Equals(value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OdaNo {
            get {
                return this.OdaNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OdaNoField, value) != true)) {
                    this.OdaNoField = value;
                    this.RaisePropertyChanged("OdaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ucret {
            get {
                return this.UcretField;
            }
            set {
                if ((object.ReferenceEquals(this.UcretField, value) != true)) {
                    this.UcretField = value;
                    this.RaisePropertyChanged("Ucret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciKayitEt", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class KullaniciKayitEt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GirisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciSifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GirisTarihi {
            get {
                return this.GirisTarihiField;
            }
            set {
                if ((this.GirisTarihiField.Equals(value) != true)) {
                    this.GirisTarihiField = value;
                    this.RaisePropertyChanged("GirisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciSifre {
            get {
                return this.KullaniciSifreField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciSifreField, value) != true)) {
                    this.KullaniciSifreField = value;
                    this.RaisePropertyChanged("KullaniciSifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                if ((object.ReferenceEquals(this.soyadField, value) != true)) {
                    this.soyadField = value;
                    this.RaisePropertyChanged("soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefon {
            get {
                return this.telefonField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonField, value) != true)) {
                    this.telefonField = value;
                    this.RaisePropertyChanged("telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonelBilgileri", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class PersonelBilgileri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BolumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CikisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GirisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolum {
            get {
                return this.BolumField;
            }
            set {
                if ((object.ReferenceEquals(this.BolumField, value) != true)) {
                    this.BolumField = value;
                    this.RaisePropertyChanged("Bolum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CikisTarihi {
            get {
                return this.CikisTarihiField;
            }
            set {
                if ((this.CikisTarihiField.Equals(value) != true)) {
                    this.CikisTarihiField = value;
                    this.RaisePropertyChanged("CikisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GirisTarihi {
            get {
                return this.GirisTarihiField;
            }
            set {
                if ((this.GirisTarihiField.Equals(value) != true)) {
                    this.GirisTarihiField = value;
                    this.RaisePropertyChanged("GirisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maas {
            get {
                return this.MaasField;
            }
            set {
                if ((object.ReferenceEquals(this.MaasField, value) != true)) {
                    this.MaasField = value;
                    this.RaisePropertyChanged("Maas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonelId {
            get {
                return this.PersonelIdField;
            }
            set {
                if ((this.PersonelIdField.Equals(value) != true)) {
                    this.PersonelIdField = value;
                    this.RaisePropertyChanged("PersonelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcNo {
            get {
                return this.TcNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNoField, value) != true)) {
                    this.TcNoField = value;
                    this.RaisePropertyChanged("TcNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MutfakU", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class MutfakU : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GelisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MutfakUIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adet {
            get {
                return this.AdetField;
            }
            set {
                if ((object.ReferenceEquals(this.AdetField, value) != true)) {
                    this.AdetField = value;
                    this.RaisePropertyChanged("Adet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((object.ReferenceEquals(this.FiyatField, value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GelisTarihi {
            get {
                return this.GelisTarihiField;
            }
            set {
                if ((this.GelisTarihiField.Equals(value) != true)) {
                    this.GelisTarihiField = value;
                    this.RaisePropertyChanged("GelisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kategori {
            get {
                return this.KategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.KategoriField, value) != true)) {
                    this.KategoriField = value;
                    this.RaisePropertyChanged("Kategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MutfakUId {
            get {
                return this.MutfakUIdField;
            }
            set {
                if ((this.MutfakUIdField.Equals(value) != true)) {
                    this.MutfakUIdField = value;
                    this.RaisePropertyChanged("MutfakUId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OdaU", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class OdaU : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GelisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OdaUIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adet {
            get {
                return this.AdetField;
            }
            set {
                if ((object.ReferenceEquals(this.AdetField, value) != true)) {
                    this.AdetField = value;
                    this.RaisePropertyChanged("Adet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((object.ReferenceEquals(this.FiyatField, value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GelisTarihi {
            get {
                return this.GelisTarihiField;
            }
            set {
                if ((this.GelisTarihiField.Equals(value) != true)) {
                    this.GelisTarihiField = value;
                    this.RaisePropertyChanged("GelisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kategori {
            get {
                return this.KategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.KategoriField, value) != true)) {
                    this.KategoriField = value;
                    this.RaisePropertyChanged("Kategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OdaUId {
            get {
                return this.OdaUIdField;
            }
            set {
                if ((this.OdaUIdField.Equals(value) != true)) {
                    this.OdaUIdField = value;
                    this.RaisePropertyChanged("OdaUId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMusteriB", ReplyAction="http://tempuri.org/IService1/UpdateMusteriBResponse")]
        int UpdateMusteriB(OtelUygulamasi.ServiceReference1.MusteriBilgileri b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMusteriB", ReplyAction="http://tempuri.org/IService1/UpdateMusteriBResponse")]
        System.Threading.Tasks.Task<int> UpdateMusteriBAsync(OtelUygulamasi.ServiceReference1.MusteriBilgileri b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMusteriB", ReplyAction="http://tempuri.org/IService1/DeleteMusteriBResponse")]
        int DeleteMusteriB(OtelUygulamasi.ServiceReference1.MusteriBilgileri b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMusteriB", ReplyAction="http://tempuri.org/IService1/DeleteMusteriBResponse")]
        System.Threading.Tasks.Task<int> DeleteMusteriBAsync(OtelUygulamasi.ServiceReference1.MusteriBilgileri b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KullaniciKayit", ReplyAction="http://tempuri.org/IService1/KullaniciKayitResponse")]
        int KullaniciKayit(OtelUygulamasi.ServiceReference1.KullaniciKayitEt k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KullaniciKayit", ReplyAction="http://tempuri.org/IService1/KullaniciKayitResponse")]
        System.Threading.Tasks.Task<int> KullaniciKayitAsync(OtelUygulamasi.ServiceReference1.KullaniciKayitEt k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Personelekle", ReplyAction="http://tempuri.org/IService1/PersonelekleResponse")]
        int Personelekle(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Personelekle", ReplyAction="http://tempuri.org/IService1/PersonelekleResponse")]
        System.Threading.Tasks.Task<int> PersonelekleAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonelB", ReplyAction="http://tempuri.org/IService1/DeletePersonelBResponse")]
        int DeletePersonelB(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonelB", ReplyAction="http://tempuri.org/IService1/DeletePersonelBResponse")]
        System.Threading.Tasks.Task<int> DeletePersonelBAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonelB", ReplyAction="http://tempuri.org/IService1/UpdatePersonelBResponse")]
        int UpdatePersonelB(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonelB", ReplyAction="http://tempuri.org/IService1/UpdatePersonelBResponse")]
        System.Threading.Tasks.Task<int> UpdatePersonelBAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMutfakU", ReplyAction="http://tempuri.org/IService1/DeleteMutfakUResponse")]
        int DeleteMutfakU(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMutfakU", ReplyAction="http://tempuri.org/IService1/DeleteMutfakUResponse")]
        System.Threading.Tasks.Task<int> DeleteMutfakUAsync(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MutfakUekle", ReplyAction="http://tempuri.org/IService1/MutfakUekleResponse")]
        int MutfakUekle(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MutfakUekle", ReplyAction="http://tempuri.org/IService1/MutfakUekleResponse")]
        System.Threading.Tasks.Task<int> MutfakUekleAsync(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMutfakU", ReplyAction="http://tempuri.org/IService1/UpdateMutfakUResponse")]
        int UpdateMutfakU(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMutfakU", ReplyAction="http://tempuri.org/IService1/UpdateMutfakUResponse")]
        System.Threading.Tasks.Task<int> UpdateMutfakUAsync(OtelUygulamasi.ServiceReference1.MutfakU m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OdaUekle", ReplyAction="http://tempuri.org/IService1/OdaUekleResponse")]
        int OdaUekle(OtelUygulamasi.ServiceReference1.OdaU o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OdaUekle", ReplyAction="http://tempuri.org/IService1/OdaUekleResponse")]
        System.Threading.Tasks.Task<int> OdaUekleAsync(OtelUygulamasi.ServiceReference1.OdaU o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOdaU", ReplyAction="http://tempuri.org/IService1/UpdateOdaUResponse")]
        int UpdateOdaU(OtelUygulamasi.ServiceReference1.OdaU o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOdaU", ReplyAction="http://tempuri.org/IService1/UpdateOdaUResponse")]
        System.Threading.Tasks.Task<int> UpdateOdaUAsync(OtelUygulamasi.ServiceReference1.OdaU o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOdaU", ReplyAction="http://tempuri.org/IService1/DeleteOdaUResponse")]
        int DeleteOdaU(OtelUygulamasi.ServiceReference1.OdaU o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOdaU", ReplyAction="http://tempuri.org/IService1/DeleteOdaUResponse")]
        System.Threading.Tasks.Task<int> DeleteOdaUAsync(OtelUygulamasi.ServiceReference1.OdaU o);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OtelUygulamasi.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OtelUygulamasi.ServiceReference1.IService1>, OtelUygulamasi.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UpdateMusteriB(OtelUygulamasi.ServiceReference1.MusteriBilgileri b) {
            return base.Channel.UpdateMusteriB(b);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMusteriBAsync(OtelUygulamasi.ServiceReference1.MusteriBilgileri b) {
            return base.Channel.UpdateMusteriBAsync(b);
        }
        
        public int DeleteMusteriB(OtelUygulamasi.ServiceReference1.MusteriBilgileri b) {
            return base.Channel.DeleteMusteriB(b);
        }
        
        public System.Threading.Tasks.Task<int> DeleteMusteriBAsync(OtelUygulamasi.ServiceReference1.MusteriBilgileri b) {
            return base.Channel.DeleteMusteriBAsync(b);
        }
        
        public int KullaniciKayit(OtelUygulamasi.ServiceReference1.KullaniciKayitEt k) {
            return base.Channel.KullaniciKayit(k);
        }
        
        public System.Threading.Tasks.Task<int> KullaniciKayitAsync(OtelUygulamasi.ServiceReference1.KullaniciKayitEt k) {
            return base.Channel.KullaniciKayitAsync(k);
        }
        
        public int Personelekle(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.Personelekle(p);
        }
        
        public System.Threading.Tasks.Task<int> PersonelekleAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.PersonelekleAsync(p);
        }
        
        public int DeletePersonelB(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.DeletePersonelB(p);
        }
        
        public System.Threading.Tasks.Task<int> DeletePersonelBAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.DeletePersonelBAsync(p);
        }
        
        public int UpdatePersonelB(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.UpdatePersonelB(p);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePersonelBAsync(OtelUygulamasi.ServiceReference1.PersonelBilgileri p) {
            return base.Channel.UpdatePersonelBAsync(p);
        }
        
        public int DeleteMutfakU(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.DeleteMutfakU(m);
        }
        
        public System.Threading.Tasks.Task<int> DeleteMutfakUAsync(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.DeleteMutfakUAsync(m);
        }
        
        public int MutfakUekle(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.MutfakUekle(m);
        }
        
        public System.Threading.Tasks.Task<int> MutfakUekleAsync(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.MutfakUekleAsync(m);
        }
        
        public int UpdateMutfakU(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.UpdateMutfakU(m);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMutfakUAsync(OtelUygulamasi.ServiceReference1.MutfakU m) {
            return base.Channel.UpdateMutfakUAsync(m);
        }
        
        public int OdaUekle(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.OdaUekle(o);
        }
        
        public System.Threading.Tasks.Task<int> OdaUekleAsync(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.OdaUekleAsync(o);
        }
        
        public int UpdateOdaU(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.UpdateOdaU(o);
        }
        
        public System.Threading.Tasks.Task<int> UpdateOdaUAsync(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.UpdateOdaUAsync(o);
        }
        
        public int DeleteOdaU(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.DeleteOdaU(o);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOdaUAsync(OtelUygulamasi.ServiceReference1.OdaU o) {
            return base.Channel.DeleteOdaUAsync(o);
        }
    }
}
